import type { Metadata } from "next";
import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";

const notoSansArabic = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  variable: "--font-noto-sans-arabic"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${notoSansArabic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
